import argparse
import os
from pathlib import Path

import pandas as pd
import requests

ROOT = Path(__file__).resolve().parent.parent


def load_stats(csv_path):
    df = pd.read_csv(csv_path)
    med = df.groupby(["input_rows", "implementation"], as_index=False).agg(
        seconds=("seconds", "median"), peak_mem_mb=("peak_mem_mb", "median")
    )
    p = med[med["implementation"] == "pandas"].set_index("input_rows")
    d = med[med["implementation"] == "duckdb"].set_index("input_rows")
    out = pd.DataFrame(
        {
            "pandas_seconds": p["seconds"],
            "duckdb_seconds": d["seconds"],
            "pandas_mem_mb": p["peak_mem_mb"],
            "duckdb_mem_mb": d["peak_mem_mb"],
        }
    ).reset_index()
    out["speedup"] = out["pandas_seconds"] / out["duckdb_seconds"]
    out["memory_ratio"] = out["duckdb_mem_mb"] / out["pandas_mem_mb"]
    return out.round(2)


def build_prompt(stats):
    return (
        "Below are benchmark results for the same data pipeline built two ways: pandas and DuckDB SQL. "
        "Columns: input_rows, time in seconds, peak memory in MB, speedup (pandas time divided by DuckDB time) "
        "and memory_ratio (DuckDB memory divided by pandas memory).\n\n"
        f"{stats.to_string(index=False)}\n\n"
        "Write 4 to 5 plain sentences. Use only numbers that appear in the table. Do not invent numbers. "
        "Say which version is better for time and which for memory, how this changes as data grows, "
        "and give a short recommendation about the cost and performance trade-off."
    )


class SummaryProvider:
    name = "base"

    def summarize(self, stats):
        raise NotImplementedError


class OllamaProvider(SummaryProvider):
    def __init__(self, model=None, url=None, timeout=60):
        self.model = model or os.environ.get("AI_MODEL", "llama3.2")
        self.url = url or os.environ.get("OLLAMA_URL", "http://localhost:11434")
        self.timeout = timeout
        self.name = f"ollama:{self.model}"

    def summarize(self, stats):
        response = requests.post(
            f"{self.url}/api/generate",
            json={"model": self.model, "prompt": build_prompt(stats), "stream": False},
            timeout=self.timeout,
        )
        response.raise_for_status()
        text = response.json().get("response", "").strip()
        if not text:
            raise ValueError("empty response from model")
        return text


class RuleBasedProvider(SummaryProvider):
    name = "rule-based"

    def summarize(self, stats):
        first = stats.iloc[0]
        last = stats.iloc[-1]
        return (
            f"At {int(first['input_rows']):,} rows, pandas took {first['pandas_seconds']:.2f}s and "
            f"DuckDB took {first['duckdb_seconds']:.2f}s. "
            f"At {int(last['input_rows']):,} rows, DuckDB SQL took {last['duckdb_seconds']:.2f}s against "
            f"{last['pandas_seconds']:.2f}s for pandas, a speedup of {last['speedup']:.1f}x. "
            f"DuckDB used {last['duckdb_mem_mb']:.0f} MB of memory against {last['pandas_mem_mb']:.0f} MB "
            f"for pandas, which is {last['memory_ratio']:.2f}x. "
            "DuckDB is the better choice when compute time is the main cost, "
            "and pandas is the safer choice when memory is limited."
        )


def get_summary(stats, provider=None):
    provider = provider or OllamaProvider()
    try:
        return provider.summarize(stats), provider.name
    except Exception:
        fallback = RuleBasedProvider()
        return fallback.summarize(stats), f"{fallback.name} (fallback)"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--metrics", default=str(ROOT / "docs" / "metrics.csv"))
    parser.add_argument("--out", default=str(ROOT / "docs" / "summary.md"))
    args = parser.parse_args()

    stats = load_stats(args.metrics)
    text, source = get_summary(stats)
    print(stats.to_string(index=False))
    print()
    print(f"source: {source}")
    print(text)

    Path(args.out).write_text(f"{text}\n\nGenerated by: {source}\n", encoding="utf-8")


if __name__ == "__main__":
    main()